import React from 'react'
import { render, fireEvent } from '@testing-library/react'
import { FetchMock, fetchMock } from '@react-mock/fetch'
import Map from './Map'

describe('Map component renders correctly', () => {
    let getAllByText, getByLabelText
    beforeEach(() => {
        ({ getAllByText, getByLabelText } = render(
            <FetchMock matcher={"*"} method='POST' response={JSON.stringify(sampleResponse)}>
                <Map />
            </FetchMock>
        ))
    })
    test('Map title visible', () => {
        getAllByText(/map/i)
    })
    test('Map visualization visible', () => {
        getByLabelText(/visualization/i)
    })
})

const sampleResponse = [
    {
      "date": "2020-04-24",
      "Afghanistan": "-95",
      "Angola": "0",
      "Albania": "0",
      "United Arab Emirates": "99",
      "Argentina": "99",
      "Armenia": "100",
      "Antarctica": "0",
      "Fr. S. Antarctic Lands": "0",
      "Australia": "37",
      "Austria": "100",
      "Azerbaijan": "100",
      "Burundi": "0",
      "Belgium": "100",
      "Benin": "0",
      "Burkina Faso": "0",
      "Bangladesh": "-99",
      "Bulgaria": "0",
      "Bahamas": "99",
      "Bosnia and Herz.": "0",
      "Belarus": "0",
      "Belize": "100",
      "Bolivia": "0",
      "Brazil": "0",
      "Brunei": "0",
      "Bhutan": "0",
      "Botswana": "0",
      "Central African Rep.": "0",
      "Canada": "33",
      "Switzerland": "100",
      "Chile": "0",
      "China": "44",
      "Côte d'Ivoire": "0",
      "Cameroon": "0",
      "Dem. Rep. Congo": "0",
      "Congo": "0",
      "Colombia": "-38",
      "Costa Rica": "0",
      "Cuba": "0",
      "N. Cyprus": "0",
      "Cyprus": "0",
      "Czechia": "0",
      "Germany": "99",
      "Djibouti": "0",
      "Denmark": "98",
      "Dominican Rep.": "0",
      "Algeria": "0",
      "Ecuador": "0",
      "Egypt": "0",
      "Eritrea": "0",
      "Spain": "34",
      "Estonia": "0",
      "Ethiopia": "95",
      "Finland": "0",
      "Fiji": "0",
      "Falkland Is.": "0",
      "France": "71",
      "Gabon": "0",
      "United Kingdom": "100",
      "Georgia": "40",
      "Ghana": "100",
      "Guinea": "0",
      "Gambia": "0",
      "Guinea-Bissau": "0",
      "Eq. Guinea": "0",
      "Greece": "0",
      "Greenland": "47",
      "Guatemala": "0",
      "Guyana": "0",
      "Honduras": "0",
      "Croatia": "0",
      "Haiti": "0",
      "Hungary": "100",
      "Indonesia": "-0",
      "India": "38",
      "Ireland": "89",
      "Iran": "-89",
      "Iraq": "0",
      "Iceland": "0",
      "Israel": "-99",
      "Italy": "-4",
      "Jamaica": "0",
      "Jordan": "98",
      "Japan": "-22",
      "Kazakhstan": "0",
      "Kenya": "0",
      "Kyrgyzstan": "0",
      "Cambodia": "0",
      "South Korea": "99",
      "Kosovo": "0",
      "Kuwait": "0",
      "Laos": "0",
      "Lebanon": "0",
      "Liberia": "0",
      "Libya": "0",
      "Sri Lanka": "0",
      "Lesotho": "0",
      "Lithuania": "0",
      "Luxembourg": "100",
      "Latvia": "0",
      "Morocco": "0",
      "Moldova": "0",
      "Madagascar": "0",
      "Mexico": "21",
      "Macedonia": "0",
      "Mali": "0",
      "Myanmar": "0",
      "Montenegro": "0",
      "Mongolia": "0",
      "Mozambique": "0",
      "Mauritania": "0",
      "Malawi": "0",
      "Malaysia": "0",
      "Namibia": "0",
      "New Caledonia": "100",
      "Niger": "0",
      "Nigeria": "0",
      "Nicaragua": "0",
      "Netherlands": "33",
      "Norway": "0",
      "Nepal": "0",
      "New Zealand": "100",
      "Oman": "0",
      "Pakistan": "0",
      "Panama": "99",
      "Peru": "0",
      "Philippines": "0",
      "Papua New Guinea": "0",
      "Poland": "100",
      "Puerto Rico": "0",
      "North Korea": "16",
      "Portugal": "0",
      "Paraguay": "0",
      "Palestine": "0",
      "Qatar": "0",
      "Romania": "0",
      "Russia": "-32",
      "Rwanda": "100",
      "W. Sahara": "0",
      "Saudi Arabia": "-97",
      "Sudan": "0",
      "S. Sudan": "0",
      "Senegal": "0",
      "Solomon Is.": "0",
      "Sierra Leone": "0",
      "El Salvador": "0",
      "Somaliland": "0",
      "Somalia": "0",
      "Serbia": "0",
      "Suriname": "0",
      "Slovakia": "0",
      "Slovenia": "0",
      "Sweden": "99",
      "Swaziland": "0",
      "Syria": "0",
      "Chad": "0",
      "Togo": "0",
      "Thailand": "0",
      "Tajikistan": "0",
      "Turkmenistan": "0",
      "Timor-Leste": "0",
      "Trinidad and Tobago": "0",
      "Tunisia": "0",
      "Turkey": "0",
      "Taiwan": "99",
      "Tanzania": "0",
      "Uganda": "100",
      "Ukraine": "99",
      "Uruguay": "0",
      "United States": "39",
      "Uzbekistan": "0",
      "Venezuela": "-78",
      "Vietnam": "-81",
      "Vanuatu": "0",
      "Yemen": "0",
      "South Africa": "27",
      "Zambia": "59",
      "Zimbabwe": "0"
    }
  ]