# Generated by Django 3.0.2 on 2020-01-24 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text_snippet', models.CharField(max_length=500)),
                ('text_full', models.TextField(default='')),
                ('score_model', models.FloatField(null=True)),
                ('score_user_numerator', models.IntegerField(default=0)),
                ('score_user_denominator', models.IntegerField(default=0)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='articles.Publisher')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
