# Generated by Django 3.0.2 on 2020-01-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200124_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='articles.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='articles',
            field=models.ManyToManyField(to='articles.Article'),
        ),
    ]
