# Generated by Django 3.0.2 on 2020-01-24 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='score_model',
            new_name='sentiment_score',
        ),
    ]
