# Generated by Django 3.0.2 on 2020-02-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200124_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('location_type', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='articles',
        ),
        migrations.AddField(
            model_name='category',
            name='taxonomy_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='url',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='article',
            name='locations',
            field=models.ManyToManyField(blank=True, to='articles.Location'),
        ),
    ]
