# Generated by Django 3.0.2 on 2020-01-17 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200116_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sentiment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 22, 54, 56, 168328)),
        ),
    ]
