# Generated by Django 3.0.2 on 2020-01-16 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 23, 25, 51, 353918)),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.CharField(default='', max_length=30),
        ),
    ]
