# Generated by Django 3.0.2 on 2020-01-16 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200116_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 23, 26, 57, 978276)),
        ),
    ]
