export const LOGIN_TRUE = "LOGIN_TRUE";
export const LOGIN_FALSE = "LOGIN_FALSE";
export const LOGIN_PENDING = "LOGIN_PENDING";
export const LOGIN_DONE = "LOGIN_DONE";
export const DATA_USER_CATEGORY = "DATA_USER_CATEGORY";
export const DATA_USER_PUBLISHER = "DATA_USER_PUBLISHER";
export const DATA_ALL_CATEGORY = "DATA_ALL_CATEGORY";
export const DATA_ALL_PUBLISHER = "DATA_ALL_PUBLISHER";
